import type { Metadata } from "next";
import { Montserrat, Roboto_Mono } from "next/font/google";
import { ThemeProvider } from "@/app/providers/theme-provider";
import "./globals.css";

const montserrat = Montserrat({ 
  weight: ['300', '400', '700'],
  style: ['normal'],
  subsets: ["latin"],
  preload: true,
  variable: '--font-montserrat'
});

const robotoMono = Roboto_Mono({
  weight: ['300'],
  style: ['normal'],
  preload: true,
  subsets: ["latin"],
  variable: '--font-roboto-mono'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${robotoMono.variable} ${montserrat.variable}`} suppressHydrationWarning>
      <ThemeProvider
        attribute="class"
        defaultTheme="system"
        enableSystem
        disableTransitionOnChange
      >
            {children}
          </ThemeProvider>
        </body>
    </html>
  );
}
